NIXPACKS_BUILD_CMD="composer install && npm i && npm run  build && php artisan migrate --force && php artisan optimize && chmod 777 -R storage/ && chmod 777 -R bootstrap/cache && php artisan storage:link"
web: php artisan serve --host=0.0.0.0 --port=${PORT}
