[phases.setup]
commands = [
  "apt-get update",
  "apt-get install -y curl",
  "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer",
  "composer --version"  # Verificar que Composer esté instalado correctamente
]